const companies = [
  {
    handle: "anderson-arias-morrow",
    name: "Anderson, Arias and Morrow",
    description:
      "Somebody program how I. Face give away discussion view act inside. Your official relationship administration here.",
    numEmployees: 245,
    logoUrl: "/logos/logo3.png",
  },
  {
    handle: "arnold-berger-townsend",
    name: "Arnold, Berger and Townsend",
    description:
      "Kind crime at perhaps beat. Enjoy deal purpose serve begin or thought. Congress everything miss tend.",
    numEmployees: 795,
    logoUrl: null,
  },
  {
    handle: "ayala-buchanan",
    name: "Ayala-Buchanan",
    description:
      "Make radio physical southern. His white on attention kitchen market upon. Represent west open seven. Particularly subject billion much score thank bag somebody.",
    numEmployees: 309,
    logoUrl: null,
  },
  {
    handle: "baker-santos",
    name: "Baker-Santos",
    description:
      "Compare certain use. Writer time lay word garden. Resource task interesting voice.",
    numEmployees: 225,
    logoUrl: "/logos/logo3.png",
  },
  {
    handle: "bauer-gallagher",
    name: "Bauer-Gallagher",
    description: "Difficult ready trip question produce produce someone.",
    numEmployees: 862,
    logoUrl: null,
  },
];

const comJobs = [
  {
    id: 66,
    title: "Camera operator",
    salary: 130000,
    equity: "0",
  },
  {
    id: 97,
    title: "Information systems manager",
    salary: 123000,
    equity: "0.100",
  },
  {
    id: 117,
    title: "Engineer, energy",
    salary: null,
    equity: "0.048",
  },
];

const jobs = [
  {
    id: 200,
    title: "Accommodation manager",
    salary: 126000,
    equity: null,
    companyHandle: "mejia-scott-ryan",
    companyName: "Mejia, Scott and Ryan",
  },
  {
    id: 36,
    title: "Accountant, chartered certified",
    salary: 175000,
    equity: "0",
    companyHandle: "stone-stewart",
    companyName: "Stone-Stewart",
  },
  {
    id: 161,
    title: "Accountant, chartered certified",
    salary: 86000,
    equity: "0.070",
    companyHandle: "boyd-evans",
    companyName: "Boyd-Evans",
  },
  {
    id: 86,
    title: "Advertising account executive",
    salary: 130000,
    equity: "0.064",
    companyHandle: "thomas-sons",
    companyName: "Thomas and Sons",
  },
  {
    id: 50,
    title: "Advertising account executive",
    salary: null,
    equity: "0",
    companyHandle: "thomas-sons",
    companyName: "Thomas and Sons",
  },
  {
    id: 134,
    title: "Aeronautical engineer",
    salary: 156000,
    equity: "0.055",
    companyHandle: "perez-miller",
    companyName: "Perez-Miller",
  },
  {
    id: 78,
    title: "Aeronautical engineer",
    salary: 135000,
    equity: "0.078",
    companyHandle: "norman-harvey",
    companyName: "Norman-Harvey",
  },
  {
    id: 172,
    title: "Agricultural consultant",
    salary: 67000,
    equity: null,
    companyHandle: "moore-plc",
    companyName: "Moore PLC",
  },
  {
    id: 89,
    title: "Air cabin crew",
    salary: 105000,
    equity: "0.077",
    companyHandle: "ingram-ferguson-rubio",
    companyName: "Ingram, Ferguson and Rubio",
  },
  {
    id: 71,
    title: "Applications developer",
    salary: 84000,
    equity: "0.091",
    companyHandle: "sellers-bryant",
    companyName: "Sellers-Bryant",
  },
  {
    id: 184,
    title: "Arboriculturist",
    salary: 191000,
    equity: "0.062",
    companyHandle: "salas-group",
    companyName: "Salas Group",
  },
  {
    id: 60,
    title: "Architectural technologist",
    salary: 57000,
    equity: "0",
    companyHandle: "owen-newton",
    companyName: "Owen-Newton",
  },
  {
    id: 158,
    title: "Armed forces technical officer",
    salary: 136000,
    equity: "0.012",
    companyHandle: "scott-smith",
    companyName: "Scott-Smith",
  },
  {
    id: 98,
    title: "Art gallery manager",
    salary: 73000,
    equity: "0.054",
    companyHandle: "perez-miller",
    companyName: "Perez-Miller",
  },
  {
    id: 62,
    title: "Art gallery manager",
    salary: null,
    equity: "0.085",
    companyHandle: "anderson-arias-morrow",
    companyName: "Anderson, Arias and Morrow",
  },
  {
    id: 47,
    title: "Astronomer",
    salary: 143000,
    equity: null,
    companyHandle: "watson-davis",
    companyName: "Watson-Davis",
  },
  {
    id: 181,
    title: "Astronomer",
    salary: 55000,
    equity: "0.074",
    companyHandle: "martinez-daniels",
    companyName: "Martinez-Daniels",
  },
  {
    id: 29,
    title: "Barrister",
    salary: 130000,
    equity: "0",
    companyHandle: "stone-stewart",
    companyName: "Stone-Stewart",
  },
];

export { companies, comJobs, jobs };
